# Generated by Django 3.0.2 on 2020-01-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=111)),
                ('images', models.TextField()),
                ('sizes', models.CharField(max_length=111)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=111)),
            ],
        ),
    ]
